import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/navbar";
import { WelcomeIntro } from "@/components/layout/welcome-intro";
import {
  GATE_INTRO_ONCE,
  INTRO_ENABLED,
  INTRO_STORAGE_KEY,
} from "@/lib/intro-storage";
import { cn } from "@/lib/utils";

const introGuard = GATE_INTRO_ONCE
  ? `try{if(localStorage.getItem(${JSON.stringify(INTRO_STORAGE_KEY)})==="true"){document.documentElement.setAttribute("data-intro","seen")}}catch(e){}`
  : "";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <head>
        {introGuard ? (
          // biome-ignore lint/security/noDangerouslySetInnerHtml: static build-time guard string, no user input
          <script dangerouslySetInnerHTML={{ __html: introGuard }} />
        ) : null}
      </head>
      <body className="min-h-full flex flex-col">
        {INTRO_ENABLED ? <WelcomeIntro /> : null}
        <Navbar />
        <div className="flex flex-1 flex-col pt-20 sm:pt-24">{children}</div>
      </body>
    </html>
  );
}
